pipeline {
    agent any
    environment {
        DOCKERHUB_PASS = credentials('docker-pass')
        IMAGE_TAG = "${env.BUILD_TIMESTAMP ?: 'latest'}"
    }
    stages {
        stage('Building the Student Survey Image') {
            steps {
                script {
                    checkout scm
                    sh 'echo ${BUILD_TIMESTAMP}'
                    sh "docker login -u gshieldsgmu -p $DOCKERHUB_PASS_PSW"
                    sh 'docker build -t gshieldsgmu/app:${IMAGE-TAG} .'
                }
            }
        }
        stage('Pushing Image to DockerHub') {
            steps {
                script {
                    sh 'docker push gshieldsgmu/app:${IMAGE-TAG}'
                }
            }
        }
        // stage('Deploying to Rancher as single pod') {
        //     steps {
        //         sh 'kubectl set image deployment/stusurvey-pipeline stusurvey-pipeline=hekme5/studentsurvey645:${BUILD_TIMESTAMP} -n jenkins-pipeline'
        //     }
        // }
        // stage('Deploying to Rancher as with load balancer') {
        //     steps {
        //         sh 'kubectl set image deployment/studentsurvey645-lb studentsurvey645-lb=hekme5/studentsurvey645:${BUILD_TIMESTAMP} -n jenkins-pipeline'
        //     }
        // }
    }
}
